### PR TITLE
More mock classes and methods missing for Elasticsearch 6

### PR DESCRIPTION
**Pull request by murdos**
New classes were needed for running Spring Data Elasticsearch 3.2.
I've also added missing methods requested in #1

### CODE REVIEW

**Comment by ctron** [comment]
Thanks for the PR. Could you re-base on master, that should fix the issue with travis.

**Comment by murdos** [comment]
I've closed/reopen the PR to relaunch the CI instead ;-)
Please tell me if you still want me to re-base on master, or if it's ready for merge.

**Comment by murdos** [comment]
Thanks for the new release! 👍

**Comment by ctron** [comment]
:+1:  Thank you for the PR!

**Pull request merged**
